command_timeout = 5000
add_newline = true

[elixir]
symbol = "ğŸ”® "

[character]                            # The name of the module we are configuring is "character"
success_symbol = "ğŸš€"     # The "success_symbol" segment is being set to "âœ" with the color "bold green"
error_symbol = "ğŸ”¥"

[gcloud]
symbol = "ï¸ğŸ‡¬ï¸ "
disabled = true
[gcloud.region_aliases]
us-east1 = "ue1"
us-central1 = "uc1"
asia-northeast1 = "an1"

[aws]
disabled = true

# [kubernetes]
# symbol =  "ğŸ›³ï¸"
# style = "cyan bold"
# format = '[$symbol$context]($style) '
# disabled = false
# [kubernetes.context_aliases]
# disabled = false
# "*" = "dev ğŸ›³ï¸"

[kubernetes]
format = '[ğŸš¢ $context\($namespace\)](dimmed cyan bold) '
disabled = false
[kubernetes.context_aliases]
# "pi-cluster" = "dev"
"gke_.*_(?P<var_cluster>[\\w-]+)" = "influx dev "
# [kubernetes.user_aliases]
# "dev.local.cluster.k8s" = "dev"
# "root/.*" = "root"

